### PR TITLE
Create linked list data structure

### PR DESCRIPTION
**Pull request by johnnyrichard**
We will need to have a list to traverse game entities.

The first idea is to implement a mutable list. If the mutable list
get too bad or error prone. We can easily change it to immutable.

Signed-off-by: Johnny Richard <johnny@johnnyrichard.com>

### CODE REVIEW

**Comment by fabiomaciel** [comment]
i think a immutable list is bad, if we use this, we have a chance to it iteration create a new list, and with this allocate more memory to it list.

**Comment by johnnyrichard** [comment]
@fabiomaciel wrote:
> i think a immutable list is bad, if we use this, we have a chance to it
> iteration create a new list, and with this allocate more memory to it list.

I'm not sure if I understood what you said here. Are you asking me to keep it
as it is? Maybe immutable is not what I wanted to express here (sorry).

The implementation today you pass a list to the functions and you don't have to
do reassign:

    list_t* list = NULL;

    list_push(&list, ptr1);
    list_push(&list, ptr2);

    assert(list->value == ptr2);
    assert(list->next->value == ptr1);

The other solution would be do reassign like below

    list_t* list = NULL;

    list = list_push(list, ptr1);
    list = list_push(list, ptr2);

    assert(list->value == ptr2);
    assert(list->next->value == ptr1);

I think it doesn't have anything to do with mutability, it's more about API.
Which one you prefer?

About optimizations I don't think we should be so strict at this phase of the
project, let's optimize on the fly and get things done first.

**Comment by fabiomaciel** [comment]
right, i not said about the code itself, i was attached to the immutable word that you said.
but i think either way are good. but maybe the first one is more intuitive.

**Comment by johnnyrichard** [comment]
> right, i not said about the code itself, i was attached to the immutable word that you said. but i think either way are good. but maybe the first one is more intuitive.

Sure, the code already implements the first API, let me know if I should change something else.

Now it is ready to review @fabiomaciel

**Pull request merged**
