### PR TITLE
Introduce hitbox object for collision logic

### PR DESCRIPTION
**Pull request by johnnyrichard**
The hitbox object is an attempt of creating an object which delimit
boundaries for players and enemies collision, it the future it can be
used to verify if a player has been collided to a object on the map.
Signed-off-by: Johnny Richard <johnny@johnnyrichard.com>

---

I'm not sure if we should call it **hitbox** or something else to make the
intention clear. I'm open for suggestions.

[v2](https://github.com/fabiomaciel/blast-attack/compare/67812f28ddbe0339a89bcbd0c729df388fc90db1..31f5e8ab7c525e946c258d7e2f3b27b14756363e):
 - Rename box to hitbox

### CODE REVIEW

**Comment by fabiomaciel** [comment]
i think maybe hitbox or collisionbox should be better to make clear what is the intention, box could be too generic. indeed box_draw make more unclear, i dont think this module should have a draw function. i think this is should be a debug functiolality, and maybe other module more especific for this should know how to draw this box.

**Comment by johnnyrichard** [comment]
@fabiomaciel  wrote:
> i think maybe hitbox or collisionbox should be better to make clear what is
> the intention, box could be too generic.

Sure. I will rename it to hitbox.

> indeed box_draw make more unclear, i dont think this module should have a
> draw function. i think this is should be a debug functiolality, and maybe
> other module more especific for this should know how to draw this box.

Yep, the draw function I have introduced for debuging proposes.

What do you think about adding a **FIXME** saying to remove it after implement
the collision logic?

**Comment by fabiomaciel** [comment]
> What do you think about adding a FIXME saying to remove it after implement
the collision logic?

yeah, good idea

**Comment by johnnyrichard** [comment]
ping @fabiomaciel

**Pull request merged**
